<?php
class CustomerEmailDB {
    /*
    * @method - addEmail($id)
    * @description - add a customers email address to DB
    * @param - customer email address
    * @param - customer ID
    */
    public static function addEmail($email, $id) {
        $db = Database::getDB();

        $query = 'INSERT INTO CUS_EMAIL(cusEmailAddress, cusID)
        VALUES (:email, :id)';

        $statement = $db->prepare($query);

        $statement->bindValue(':email', $email);
        $statement->bindValue(':id', $id);

        $success = $statement->execute();

        if ($success) { // check query was successfully executed
            $count = $statement->rowCount();
            if ($count == 0) { // ensure that a row was inserted
                return 0;
            } else { // return autogenerated ID
                return $db->lastInsertID();
            }
        } else {
            return 0;
        }
    }

}
?>
