<?php

class InvoiceItemDB {

    /**
    * @method - addInvoiceItem($item)
    * @description - add InvoiceItem to DB
    * @param - $item - invoice Item Object
    * @return integer representing the auto generated ID or 0 for no rows affected or if query did not execute at all
    */
    public static function addInvoiceItem($item) {
        $db = Database::getDB();

        $itemQty = $item->getQuantity();
        $sold = $item->getSoldPrice();
        $total = $item->getTotalPrice();
        $supID = $item->getSupplementID();
        $invID = $item->getInvID();

        $query = 'INSERT INTO INVOICE_ITEM (itmQty, itmSoldPrice, itmTotalPrice, supID, invID)
        VALUES (:qty, :sold, :total, :supID, :invID)';

        $statement = $db->prepare($query);

        $statement->bindValue(':qty', $itemQty);
        $statement->bindValue(':sold', $sold);
        $statement->bindValue(':total', $total);
        $statement->bindValue(':supID', $supID);
        $statement->bindValue(':invID', $invID);

        $success = $statement->execute();

        if ($success) { // check query was successfully executed
            $count = $statement->rowCount();
            if ($count == 0) { // ensure that a row was inserted
                return 0;
            } else { // return autogenerated ID
                return $db->lastInsertID();
            }
        } else {
            return 0;
        }
    }

    /**
    * @method - deleteInvoiceItems($invID)
    * @description - delete the invoice items associated with an invoice
    * @param - $invID - the invoice id
    * @return - boolean value represnting if the operation was a success
    */
    public static function deleteInvoiceItems($invID) {
        $db = Database::getDB();

        $query = 'DELETE FROM INVOICE_ITEM
        WHERE invID = :invID';

        $statement = $db->prepare($query);

        $statement->bindValue(':invID', $invID);

        $rowCount = $statement->execute();

        if ($rowCount > 0) { // check query was successfully executed
            return true;
        } else {
            return false;
        }

    }

} // end of class

?>
