<footer id="subFooter">
    <section class="sf-left">
        <h4 class="sf-head">Get to know us</h4>
        <ul class="sf-list">
            <li><a href="index.php?action=about" class="sf-text">Who are we</a></li>
            <li><a href="index.php?action=contact" class="sf-text">Where are we</a></li>
            <li><a href="index.php?action=contact" class="sf-text">Contact us</a></li>
        </ul>
    </section>

    <section class="sf-center">
        <h4 class="sf-head sf-head-center">Follow us</h4>
        <figure class="sf-icon">
            <a href="https://web.facebook.com/lee.walker.75436531" class="fa fa-facebook"></a>
            <a href="https://twitter.com/MyVitalityTK" class="fa fa-twitter"></a>
            <a href="https://www.instagram.com/myvitalitytk/?hl=en" class="fa fa-instagram"></a>
        </figure>
    </section>

    <section class="sf-right">
        <h4 class="sf-head">Let us help you</h4>
        <ul class="sf-list sf-list-bottom">
            <li><a href="documents/user_manual.pdf" target="_blank" class="sf-text">User manual</a></li>
            <li><a href="index.php?action=terms-conditions" class="sf-text">Terms and conditions</a></li>
            <li><a href="index.php?action=how-to-pay" class="sf-text">How to pay</a></li>
        </ul>
    </section>
</footer>
