<!-- logo  -->
<header id="mainHeader">
    <img id="logo" src="../images/logo.png" alt="My Vitality logo" class="resizeable"/>
</header>

<!-- logo, cart -->
<header id="mainHeader">
    <img id="logo" src="../images/logo.png" alt="My Vitality logo" class="resizeable"/>
    <a href="index.php?action=logout" class="cart"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
</header>
