<!-- administration site navigation used for general administrator -->
<nav id="navHeader">
    <ul class="nav">
        <li><a href="index.php?action=home">Home</a></li>
        <li><a href="index.php?action=shipment">Shipment</a>
            <ul>
                <li><a href="index.php?action=shipped-shipment">Sent</a></li>
            </ul>
        </li>
        <li><a href="index.php?action=stock">Stock</a>
            <ul>
                <li><a href="index.php?action=purchase-journal">Journal</a></li>
            </ul>
        </li>
    </ul>
</nav>
 
