<!-- full administration site navigation used for superuser -->
<nav id="navHeader">
    <ul class="nav">
        <li><a href="index.php?action=home">Home</a></li>
        <li><a href="index.php?action=mis">MIS</a></li>
        <li><a href="index.php?action=orders">Order</a>
            <ul>
                <li><a href="index.php?action=approved-orders">Approved</a></li>
                <li><a href="index.php?action=canceled-orders">Canceled</a></li>
                <li><a href="index.php?action=shipped-orders">Shipped</a></li>
            </ul>
        </li>
        <li><a href="index.php?action=shipment">Shipment</a>
            <ul>
                <li><a href="index.php?action=shipped-shipment">Sent</a></li>
            </ul>
        </li>
        <li><a href="index.php?action=stock">Stock</a>
            <ul>
                <li><a href="index.php?action=purchase-journal">Journal</a></li>
            </ul>
        </li>
    </ul>
</nav>
 
